#!/bin/sh

if [ "$#" -gt 1 ]; then
	echo "You just add 1 argument which is the commit message"
	echo "Usage: gitscript commit_message"
	exit 1
fi

if [ "$#" -eq 0 ]; then
	echo "You just add 1 argument which is the commit message"
	echo "Usage: gitscript commit_message"
	exit 1
fi

commitmsg=$1

git pull origin master
git add --all
git commit -m "$1"
git push origin master
